apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-projects
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/fred4impact/gitops-repo.git
        revision: HEAD
        directories:
          - path: envs/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/fred4impact/gitops-repo.git
        targetRevision: master
        path: apps/springbook
        helm:
          valueFiles:
            - ../../envs/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
