{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ include "springbook.namespace" . }}
  labels:
    app: {{ .Values.mysql.name }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: rootpassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: database
          readinessProbe:
            tcpSocket:
              port: {{ .Values.mysql.port }}
            initialDelaySeconds: {{ .Values.mysql.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.mysql.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.mysql.readinessProbe.periodSeconds }}
          {{- with .Values.mysql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  namespace: {{ include "springbook.namespace" . }}
  labels:
    app: {{ .Values.mysql.name }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: TCP
  selector:
    app: {{ .Values.mysql.name }}
{{- end }}
