{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
  namespace: {{ include "springbook.namespace" . }}
  labels:
    app: {{ .Values.mysql.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: {{ .Values.mysql.auth.username | quote }}
  password: {{ .Values.mysql.auth.password | quote }}
  rootpassword: {{ .Values.mysql.auth.rootPassword | quote }}
  database: {{ .Values.mysql.auth.database | quote }}
{{- end }}
