generators:
  - list:
      elements:
        - env: dev
        - env: stage
        - env: prod

template:
  metadata:
    name: springbook-{{env}}
    labels:
      env: "{{env}}"

  spec:
    project: default

    source:
      repoURL: https://github.com/fred4impact/gitops-repo.git
      targetRevision: HEAD
      path: apps/springbook
      helm:
        releaseName: springbook-{{env}}
        valueFiles:
          - ../../environments/{{env}}/values.yaml

    destination:
      server: https://kubernetes.default.svc
      namespace: springbook-{{env}}

    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true